// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqtocvwhxrzapbqcsrxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxdG9jdndoeHJ6YXBicWNzcnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Mzg1NDEsImV4cCI6MjA3MTUxNDU0MX0.h0LVtMB6LEdAD1NBZXO550wzES2MQA2yTC9N-B4tglI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});